
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Admin
 */
public class UpdateUI extends javax.swing.JFrame {

    private MobilePlan plan;
    private UserUI userUI;
    private AdminUI adminUI;

    /**
     * Creates new form UpdateUI
     *
     * @param plan
     * @param userUI
     */
    public UpdateUI(MobilePlan plan, UserUI userUI) {
        this.plan = plan;
        this.userUI = userUI;
        initComponents();
        planIDText.setText(plan.getId() + "");
        planUsernameText.setText(plan.getUserName());
        planMobileModelText.setText(plan.getMobilePhone().getMobileModel());
        planMobileOSComboBox.setSelectedItem(plan.getMobilePhone().getMobileType().toString());
        planMobileMemorySizeText.setText(plan.getMobilePhone().getMemorySize() + "");
        planMobilePriceText.setText(plan.getMobilePhone().getPrice() + "");
        planInternetQuotaText.setText(plan.getInternetQuota() + "");
        planCapLimitText.setText(plan.getCapLimit() + "");
        planDateDayText.setText(plan.getExpiryDate().getDateDay() + "");
        planDateMonthText.setText(plan.getExpiryDate().getDateMonth() + "");
        planDateYearText.setText(plan.getExpiryDate().getDateYear() + "");
        if (plan instanceof PersonalPlan) {
            planCityOrABNLabel.setText("City");
            planCityOrABNText.setText(((PersonalPlan) plan).getCity());
            personalPlanRadioButton.setSelected(true);
            planNOPText.setVisible(false);
            planNumberOfEmployeesLabel.setVisible(false);
        } else {
            planCityOrABNLabel.setText("ABN");
            planCityOrABNText.setText(((BusinessPlan) plan).getABN() + "");
            businessPlanRadioButton.setSelected(true);
            planNOPText.setText(((BusinessPlan) plan).getNumberOfEmployee() + "");
            planNOPText.setVisible(true);
            planNumberOfEmployeesLabel.setVisible(true);
        }
    }

    public UpdateUI(MobilePlan plan, AdminUI adminUI) {
        this.plan = plan;
        this.adminUI = adminUI;
        initComponents();
        planIDText.setText(plan.getId() + "");
        planUsernameText.setText(plan.getUserName());
        planMobileModelText.setText(plan.getMobilePhone().getMobileModel());
        planMobileOSComboBox.setSelectedItem(plan.getMobilePhone().getMobileType().toString());
        planMobileMemorySizeText.setText(plan.getMobilePhone().getMemorySize() + "");
        planMobilePriceText.setText(plan.getMobilePhone().getPrice() + "");
        planInternetQuotaText.setText(plan.getInternetQuota() + "");
        planCapLimitText.setText(plan.getCapLimit() + "");
        planDateDayText.setText(plan.getExpiryDate().getDateDay() + "");
        planDateMonthText.setText(plan.getExpiryDate().getDateMonth() + "");
        planDateYearText.setText(plan.getExpiryDate().getDateYear() + "");
        if (plan instanceof PersonalPlan) {
            planCityOrABNLabel.setText("City");
            planCityOrABNText.setText(((PersonalPlan) plan).getCity());
            personalPlanRadioButton.setSelected(true);
            planNOPText.setVisible(false);
            planNumberOfEmployeesLabel.setVisible(false);
        } else {
            planCityOrABNLabel.setText("ABN");
            planCityOrABNText.setText(((BusinessPlan) plan).getABN() + "");
            businessPlanRadioButton.setSelected(true);
            planNOPText.setText(((BusinessPlan) plan).getNumberOfEmployee() + "");
            planNOPText.setVisible(true);
            planNumberOfEmployeesLabel.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        personalPlanRadioButton = new javax.swing.JRadioButton();
        businessPlanRadioButton = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        planIDLabel = new javax.swing.JLabel();
        planIDText = new javax.swing.JTextField();
        usernameLabel = new javax.swing.JLabel();
        planUsernameText = new javax.swing.JTextField();
        planCityOrABNLabel = new javax.swing.JLabel();
        planCityOrABNText = new javax.swing.JTextField();
        planNumberOfEmployeesLabel = new javax.swing.JLabel();
        planNOPText = new javax.swing.JTextField();
        internetQuotaLabel = new javax.swing.JLabel();
        planInternetQuotaText = new javax.swing.JTextField();
        planCapLimitText = new javax.swing.JTextField();
        capLimitLabel = new javax.swing.JLabel();
        generalInformationLabel1 = new javax.swing.JLabel();
        mobilePhoneTitleLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        mobilePhoneModelLabel = new javax.swing.JLabel();
        mobilePhoneOSLabel = new javax.swing.JLabel();
        planMobileModelText = new javax.swing.JTextField();
        planMobileOSComboBox = new javax.swing.JComboBox<>();
        mobileModelMemorySizeLabel = new javax.swing.JLabel();
        planMobileMemorySizeText = new javax.swing.JTextField();
        mobileModelPriceLabel = new javax.swing.JLabel();
        planMobilePriceText = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        planDateDayText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        planDateMonthText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        planDateYearText = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        planUpdateButton = new javax.swing.JButton();
        planClearButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        personalPlanRadioButton.setSelected(true);
        personalPlanRadioButton.setText("Personal Plan");
        personalPlanRadioButton.setEnabled(false);
        personalPlanRadioButton.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                personalPlanRadioButtonStateChanged(evt);
            }
        });

        businessPlanRadioButton.setText("Business Plan");
        businessPlanRadioButton.setEnabled(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        planIDLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        planIDLabel.setForeground(new java.awt.Color(102, 102, 102));
        planIDLabel.setText("Plan ID");

        planIDText.setEditable(false);

        usernameLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(102, 102, 102));
        usernameLabel.setText("Username");

        planCityOrABNLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        planCityOrABNLabel.setForeground(new java.awt.Color(102, 102, 102));
        planCityOrABNLabel.setText("City");

        planNumberOfEmployeesLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        planNumberOfEmployeesLabel.setForeground(new java.awt.Color(102, 102, 102));
        planNumberOfEmployeesLabel.setText("Number of Employees");

        internetQuotaLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        internetQuotaLabel.setForeground(new java.awt.Color(102, 102, 102));
        internetQuotaLabel.setText("Internet Quota");

        capLimitLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        capLimitLabel.setForeground(new java.awt.Color(102, 102, 102));
        capLimitLabel.setText("Cap Limit");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(planIDLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(planCityOrABNLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(117, 117, 117))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(planUsernameText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(planIDText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(planCityOrABNText, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(planNOPText, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(usernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(planNumberOfEmployeesLabel))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(planInternetQuotaText, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(internetQuotaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(capLimitLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(planCapLimitText, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(29, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(planIDLabel)
                    .addComponent(planCityOrABNLabel))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(planIDText, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(planCityOrABNText, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(planNumberOfEmployeesLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(usernameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(planUsernameText, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(planNOPText))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(internetQuotaLabel)
                    .addComponent(capLimitLabel))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(planInternetQuotaText, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(planCapLimitText, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        generalInformationLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        generalInformationLabel1.setForeground(new java.awt.Color(51, 51, 51));
        generalInformationLabel1.setText("General Information");

        mobilePhoneTitleLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        mobilePhoneTitleLabel1.setForeground(new java.awt.Color(51, 51, 51));
        mobilePhoneTitleLabel1.setText("Mobile Phone");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Expiry Date");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        mobilePhoneModelLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mobilePhoneModelLabel.setForeground(new java.awt.Color(102, 102, 102));
        mobilePhoneModelLabel.setText("Model");

        mobilePhoneOSLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mobilePhoneOSLabel.setForeground(new java.awt.Color(102, 102, 102));
        mobilePhoneOSLabel.setText("OS Type");

        planMobileOSComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Android", "IOS", "Windows" }));

        mobileModelMemorySizeLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mobileModelMemorySizeLabel.setForeground(new java.awt.Color(102, 102, 102));
        mobileModelMemorySizeLabel.setText("Memory Size");

        mobileModelPriceLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mobileModelPriceLabel.setForeground(new java.awt.Color(102, 102, 102));
        mobileModelPriceLabel.setText("Price");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mobilePhoneOSLabel)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(planMobileOSComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(planMobileModelText, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mobilePhoneModelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(planMobileMemorySizeText, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(planMobilePriceText, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mobileModelPriceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mobileModelMemorySizeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mobilePhoneModelLabel)
                    .addComponent(mobileModelMemorySizeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(planMobileModelText, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(planMobileMemorySizeText, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mobilePhoneOSLabel)
                    .addComponent(mobileModelPriceLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(planMobileOSComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(planMobilePriceText, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Day");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Month");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Year");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(planDateMonthText, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(planDateYearText, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(planDateDayText, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addGap(4, 4, 4)
                .addComponent(planDateDayText, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(planDateMonthText, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(planDateYearText, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        planUpdateButton.setBackground(new java.awt.Color(255, 153, 0));
        planUpdateButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        planUpdateButton.setForeground(new java.awt.Color(255, 255, 255));
        planUpdateButton.setText("Update");
        planUpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                planUpdateButtonActionPerformed(evt);
            }
        });

        planClearButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        planClearButton.setForeground(new java.awt.Color(255, 102, 0));
        planClearButton.setText("Clear");
        planClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                planClearButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(planClearButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(planUpdateButton, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(planUpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(planClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(generalInformationLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(156, 156, 156)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(personalPlanRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(businessPlanRadioButton))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(mobilePhoneTitleLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(personalPlanRadioButton)
                    .addComponent(businessPlanRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(generalInformationLabel1)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(38, 38, 38)
                .addComponent(mobilePhoneTitleLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void personalPlanRadioButtonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_personalPlanRadioButtonStateChanged
        if (personalPlanRadioButton.isSelected()) {
            planNOPText.setVisible(false);
            planNumberOfEmployeesLabel.setVisible(false);
            planCityOrABNLabel.setText("City");
        } else {
            planNOPText.setVisible(true);
            planNumberOfEmployeesLabel.setVisible(true);
            planCityOrABNLabel.setText("ABN");
        }
    }//GEN-LAST:event_personalPlanRadioButtonStateChanged

    private void planUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_planUpdateButtonActionPerformed
        try {
            plan.setUserName(planUsernameText.getText());
            plan.getMobilePhone().setModel(planMobileModelText.getText());
            plan.getMobilePhone().setMobileType((String) planMobileOSComboBox.getSelectedItem());
            plan.getMobilePhone().setMemorySize(Integer.parseInt(planMobileMemorySizeText.getText()));
            plan.getMobilePhone().setPrice(Double.parseDouble(planMobilePriceText.getText()));
            plan.setInternetQuota(Integer.parseInt(planInternetQuotaText.getText()));
            plan.setCapLimit(Integer.parseInt(planCapLimitText.getText()));
            plan.getExpiryDate().setDay(Integer.parseInt(planDateDayText.getText()));
            plan.getExpiryDate().setMonth(Integer.parseInt(planDateMonthText.getText()));
            plan.getExpiryDate().setYear(Integer.parseInt(planDateYearText.getText()));
            if (plan instanceof PersonalPlan) {
                plan.setCity(planCityOrABNText.getText());
            } else {
                ((BusinessPlan) plan).setABN(Integer.parseInt(planCityOrABNText.getText()));
                ((BusinessPlan) plan).setNumberOfEmployee(Integer.parseInt(planNOPText.getText()));
            }
            JOptionPane.showMessageDialog(this, "Plan has been updated successfuly");
            if (userUI != null) {
                userUI.fillPlanInformationTable();
            }
            if (adminUI != null) {
                adminUI.fillPlanInformationTable();
            }
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_planUpdateButtonActionPerformed

    private void planClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_planClearButtonActionPerformed
        planIDText.setText("");
        planUsernameText.setText("");
        planMobileModelText.setText("");
        planMobileMemorySizeText.setText("");
        planMobilePriceText.setText("");
        planDateDayText.setText("");
        planDateMonthText.setText("");
        planDateYearText.setText("");
        planCityOrABNText.setText("");
        planNOPText.setText("");
        planInternetQuotaText.setText("");
        planCapLimitText.setText("");
    }//GEN-LAST:event_planClearButtonActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(UpdateUI.class
//                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
//
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(UpdateUI.class
//                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
//
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(UpdateUI.class
//                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
//
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(UpdateUI.class
//                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new UpdateUI().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton businessPlanRadioButton;
    private javax.swing.JLabel capLimitLabel;
    private javax.swing.JLabel generalInformationLabel1;
    private javax.swing.JLabel internetQuotaLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel mobileModelMemorySizeLabel;
    private javax.swing.JLabel mobileModelPriceLabel;
    private javax.swing.JLabel mobilePhoneModelLabel;
    private javax.swing.JLabel mobilePhoneOSLabel;
    private javax.swing.JLabel mobilePhoneTitleLabel1;
    private javax.swing.JRadioButton personalPlanRadioButton;
    private javax.swing.JTextField planCapLimitText;
    private javax.swing.JLabel planCityOrABNLabel;
    private javax.swing.JTextField planCityOrABNText;
    private javax.swing.JButton planClearButton;
    private javax.swing.JTextField planDateDayText;
    private javax.swing.JTextField planDateMonthText;
    private javax.swing.JTextField planDateYearText;
    private javax.swing.JLabel planIDLabel;
    private javax.swing.JTextField planIDText;
    private javax.swing.JTextField planInternetQuotaText;
    private javax.swing.JTextField planMobileMemorySizeText;
    private javax.swing.JTextField planMobileModelText;
    private javax.swing.JComboBox<String> planMobileOSComboBox;
    private javax.swing.JTextField planMobilePriceText;
    private javax.swing.JTextField planNOPText;
    private javax.swing.JLabel planNumberOfEmployeesLabel;
    private javax.swing.JButton planUpdateButton;
    private javax.swing.JTextField planUsernameText;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
