
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Borhan
 */
public class UpdateUserUI extends javax.swing.JFrame {

    private User user;
    private ArrayList<String> citiesList;
    private AdminUI adminUI;

    /**
     * Creates new form UpdateUserUI
     */
    public UpdateUserUI(User user, ArrayList<String> cities, AdminUI adminUI) {
        this.user = user;
        this.citiesList = cities;
        this.adminUI = adminUI;
        initComponents();
        userIDText.setText(user.getUserID() + "");
        userNameText.setText(user.getName());
        userUsernameText.setText(user.getUsername());
        userPasswordText.setText(user.getPassword());
        userAddressStreetNumberText.setText(user.getAddress().getStreetNum() + "");
        userAddressStreetText.setText(user.getAddress().getStreet());
        userAddressSuburbText.setText(user.getAddress().getSuburb());
        userAddressCityText.setText(user.getAddress().getCity());
        citiesComboBox.setModel(new DefaultComboBoxModel<String>(citiesList.toArray(new String[0])));
        citiesComboBox.setSelectedItem(user.getCity());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
////    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        userIDText = new javax.swing.JTextField();
        userNameText = new javax.swing.JTextField();
        userUsernameText = new javax.swing.JTextField();
        userPasswordText = new javax.swing.JTextField();
        userIDLabel = new javax.swing.JLabel();
        userNameLabel = new javax.swing.JLabel();
        userPasswordLabel = new javax.swing.JLabel();
        personalInformationLabel = new javax.swing.JLabel();
        userUsernameLabel = new javax.swing.JLabel();
        userAdressInfoLabel = new javax.swing.JLabel();
        userAdressStreetNumberLabel = new javax.swing.JLabel();
        userAddressStreetLabel = new javax.swing.JLabel();
        userAddressSuburbLabel = new javax.swing.JLabel();
        userAddressCityLabel = new javax.swing.JLabel();
        userAddressStreetNumberText = new javax.swing.JTextField();
        userAddressStreetText = new javax.swing.JTextField();
        userAddressSuburbText = new javax.swing.JTextField();
        userAddressCityText = new javax.swing.JTextField();
        userCityChoiceCheckBox = new javax.swing.JCheckBox();
        citiesComboBox = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        userChangeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        userIDText.setEditable(false);
        userIDText.setBackground(new java.awt.Color(255, 255, 255));
        userIDText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        userIDText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        userIDText.setText("jTextField1");

        userNameText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        userNameText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        userNameText.setText("jTextField1");

        userUsernameText.setBackground(new java.awt.Color(255, 255, 255));
        userUsernameText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        userUsernameText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        userUsernameText.setText("jTextField1");

        userPasswordText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        userPasswordText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        userPasswordText.setText("jTextField1");

        userIDLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        userIDLabel.setForeground(new java.awt.Color(102, 102, 102));
        userIDLabel.setText("ID");

        userNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        userNameLabel.setForeground(new java.awt.Color(102, 102, 102));
        userNameLabel.setText("Name");

        userPasswordLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        userPasswordLabel.setForeground(new java.awt.Color(102, 102, 102));
        userPasswordLabel.setText("Password");

        personalInformationLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        personalInformationLabel.setForeground(new java.awt.Color(51, 51, 51));
        personalInformationLabel.setText("Personal Information");

        userUsernameLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        userUsernameLabel.setForeground(new java.awt.Color(102, 102, 102));
        userUsernameLabel.setText("Username");

        userAdressInfoLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        userAdressInfoLabel.setForeground(new java.awt.Color(51, 51, 51));
        userAdressInfoLabel.setText("Address Information");

        userAdressStreetNumberLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        userAdressStreetNumberLabel.setForeground(new java.awt.Color(102, 102, 102));
        userAdressStreetNumberLabel.setText("Street Number");

        userAddressStreetLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        userAddressStreetLabel.setForeground(new java.awt.Color(102, 102, 102));
        userAddressStreetLabel.setText("Street");

        userAddressSuburbLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        userAddressSuburbLabel.setForeground(new java.awt.Color(102, 102, 102));
        userAddressSuburbLabel.setText("Suburb ");

        userAddressCityLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        userAddressCityLabel.setForeground(new java.awt.Color(102, 102, 102));
        userAddressCityLabel.setText("City");

        userAddressStreetNumberText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        userAddressStreetNumberText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        userAddressStreetNumberText.setText("jTextField1");

        userAddressStreetText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        userAddressStreetText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        userAddressStreetText.setText("jTextField1");

        userAddressSuburbText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        userAddressSuburbText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        userAddressSuburbText.setText("jTextField1");

        userAddressCityText.setEditable(false);
        userAddressCityText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        userAddressCityText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        userAddressCityText.setText("jTextField1");

        userCityChoiceCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        userCityChoiceCheckBox.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        userCityChoiceCheckBox.setForeground(new java.awt.Color(51, 51, 51));
        userCityChoiceCheckBox.setText("New City");
        userCityChoiceCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userCityChoiceCheckBoxActionPerformed(evt);
            }
        });

        citiesComboBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        citiesComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 153, 0));
        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        userChangeButton.setBackground(new java.awt.Color(255, 153, 0));
        userChangeButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        userChangeButton.setForeground(new java.awt.Color(255, 255, 255));
        userChangeButton.setText("Update");
        userChangeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userChangeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(userAddressStreetLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(userIDLabel)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(userNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(userUsernameLabel)
                                                        .addComponent(userPasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(userAdressStreetNumberLabel))
                                                    .addGap(30, 30, 30))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(userAddressSuburbLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addGap(31, 31, 31)))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(userAddressCityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(31, 31, 31)))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(userNameText)
                                            .addComponent(userIDText)
                                            .addComponent(userUsernameText)
                                            .addComponent(userAddressStreetNumberText)
                                            .addComponent(userAddressStreetText)
                                            .addComponent(userAddressSuburbText)
                                            .addComponent(citiesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(userCityChoiceCheckBox)
                                                .addGap(18, 18, 18)
                                                .addComponent(userAddressCityText, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
                                            .addComponent(userPasswordText))))
                                .addGap(20, 20, 20))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(userAdressInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(personalInformationLabel)
                                .addGap(10, 10, 10))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(userChangeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(personalInformationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(userIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(userIDText)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userUsernameText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(userUsernameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(userNameText, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userPasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userPasswordText, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(userAdressInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userAdressStreetNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userAddressStreetNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userAddressStreetLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(userAddressStreetText, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userAddressSuburbLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userAddressSuburbText, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userAddressCityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(citiesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userCityChoiceCheckBox)
                    .addComponent(userAddressCityText, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userChangeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userCityChoiceCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userCityChoiceCheckBoxActionPerformed
        if (userCityChoiceCheckBox.isSelected()) {
            userAddressCityText.setEditable(true);
        } else {
            userAddressCityText.setEditable(false);
        }
    }//GEN-LAST:event_userCityChoiceCheckBoxActionPerformed

    private void userChangeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userChangeButtonActionPerformed
        try {
            user.setUsername(userUsernameText.getText());
            user.setName(userNameText.getText());
            user.setPassword(userPasswordText.getText());
            user.getAddress().setStreetNum(Integer.parseInt(userAddressStreetNumberText.getText()));
            user.getAddress().setStreet(userAddressStreetText.getText());
            user.getAddress().setSuburb(userAddressSuburbText.getText());
            if (userCityChoiceCheckBox.isSelected()) {
                user.getAddress().setCity(userAddressCityText.getText());
                citiesList.add(userAddressCityText.getText());
                citiesComboBox.setModel(new DefaultComboBoxModel<String>(citiesList.toArray(new String[0])));
                citiesComboBox.setSelectedItem(user.getCity());
            } else {
                user.getAddress().setCity((String) citiesComboBox.getSelectedItem());
                userAddressCityText.setText(user.getAddress().getCity());
            }
            adminUI.fillUserInformationTable();
            JOptionPane.showMessageDialog(this, "User has Been updated successfuly!");
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_userChangeButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(UpdateUserUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(UpdateUserUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(UpdateUserUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(UpdateUserUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new UpdateUserUI().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> citiesComboBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel personalInformationLabel;
    private javax.swing.JLabel userAddressCityLabel;
    private javax.swing.JTextField userAddressCityText;
    private javax.swing.JLabel userAddressStreetLabel;
    private javax.swing.JTextField userAddressStreetNumberText;
    private javax.swing.JTextField userAddressStreetText;
    private javax.swing.JLabel userAddressSuburbLabel;
    private javax.swing.JTextField userAddressSuburbText;
    private javax.swing.JLabel userAdressInfoLabel;
    private javax.swing.JLabel userAdressStreetNumberLabel;
    private javax.swing.JButton userChangeButton;
    private javax.swing.JCheckBox userCityChoiceCheckBox;
    private javax.swing.JLabel userIDLabel;
    private javax.swing.JTextField userIDText;
    private javax.swing.JLabel userNameLabel;
    private javax.swing.JTextField userNameText;
    private javax.swing.JLabel userPasswordLabel;
    private javax.swing.JTextField userPasswordText;
    private javax.swing.JLabel userUsernameLabel;
    private javax.swing.JTextField userUsernameText;
    // End of variables declaration//GEN-END:variables
}
